### ISSUE TITLE
Add task while creating a new entry

### ISSUE THREAD

**Issue by Mjvolk3** [lucassabreu/clockify-cli#216]
Would it be possible to create an option to add a task after running `clockify-cli in`? I am thinking of an option that looks like "No Task" but is instead "Add Task" ? My usual workflow is I see the task isn't populated yet so I back out (image below), create the task, then start again.
![image](https://user-images.githubusercontent.com/48566106/185202695-205dbaba-43a5-4a2f-baac-fbc64c002a39.png)

**Comment by lucassabreu** [comment]
i think it would be too complicated to do it, because i can't know if the user can create a task for example.

but one workaround is to create the time entry with no task, than use `clockify-cli task add` to create the task, and `clockify-cli edit current --task <id> -i=0` or `clockify-cli edit current -i` to set the task after.
