### ISSUE TITLE
task done and task add

### ISSUE THREAD

**Issue by Mjvolk3** [lucassabreu/clockify-cli#235]
Would it be possible to allow for the `task add` command to follow the same pattern as `task done`?  For instance, I would like to write `clockify-cli task -p project-name add task-name` similar to `clockify-cli task -p project-name done task-name`. Currently I have to use `clockify-cli task -p project-name  add -n task-name`. I always forget this flag when trying to make a task quickly. Is see that the flag for `add` necessary since there are other options like `--assignee` and `--billable`?

**Comment by lucassabreu** [comment]
i do think it is necessary, the arg on the `task done` and other task subcommands are for the id, but if the `allow-name-for-id` is enabled it will lookup the id of the first task that matches it.

is like rest url patters creation (`post /task`) does not accept an id, because is creating it, but the others do to select an entity (`delete /task/{id}`, `put /task/{id}`, etc).

thank you for the suggestion, but i don't think is a improvement to change it.
