### ISSUE TITLE
No timeInterval.duration in Json and go text templat format

### ISSUE THREAD

**Issue by DarkCat5501** [lucassabreu/clockify-cli#248]
I'm am integrating clockify-cli into my i3blocks and rofi scripts, but timeInterval.duration is not beeing computed for JSON output and also before text template, the function time.Since is also not available inside Go's text template, so it gives me no easy way of getting the duration

But it seems that for table it is computed and shown:

![image](https://github.com/lucassabreu/clockify-cli/assets/34375081/71525c53-5b13-49af-9e62-1ec192f7a35c)

**Comment by lucassabreu** [comment]
hi @DarkCat5501 , i implemented two functions (since and until) on the template to help to get a duration from a a open ended time entry, like this:

```sh
❯ clockify-cli show --format '{{.TimeInterval.Start|until (.TimeInterval.End|now) }}'
PT1H47M51S
```

i will not change the `--json` behaviour because the ideia I have for it to be close to the return from clockify's API, and they return as null.

you can try out those functions in the v0.45.0 version.
